import { Product, DetailedProduct } from "./types";
export const categories: Record<string, DetailedProduct[]> = {

    cocina: [
       //SIEMPRE DEBE SER DIFERENTE DE ID ESTE VA HACER DE 20-39
        {

          id: "20",
          name: "Maquinas De Obleas Lisa 16CM",
          price: 150.0,
          image: "/Cocina/MO lisa 16 cm.png",
          rating: 4,
          filter: "Maquinas de Obleas",
          category: "Cocina",
          fullDescription: [
            "Protector solar mineral tintado transparente:",
            "- Tinte universal para todos los tonos de piel.",
            "- Deja la piel con un brillo saludable al instante.",
            "- Compensa el yeso blanco típicamente asociado con los protectores solares minerales.",
            "- Ligero, sensación no grasa.",
            "",
            "Protector solar facial hidratante:",
            "- Formulado con niacinamida para calmar la piel.",
            "- Contiene ácido hialurónico para ayudar a retener la humedad natural de la piel.",
            "- Hidratante tintado con SPF 30.",
            "- Puede llevarse solo o debajo del maquillaje como una imprimación teñida con SPF 30.",
            "",
            "Adecuado para todo tipo de piel:",
            "- Incluyendo piel seca, sensible, grasa y propensa al acné.",
            "- No viene con un sello protector.",
            "",
            "Tres ceramidas esenciales:",
            "- Las ceramidas se encuentran naturalmente en la piel y pueden dañarse con la exposición al sol.",
            "- Todos los productos CeraVe están formulados con tres ceramidas esenciales (1, 3, 6-II) para ayudar a restaurar y mantener la barrera natural de la piel.",
            "",
            "Fórmula segura y suave:",
            "- Sin oxibenzona, sin avobenzona y sin benceno.",
            "- Protector solar 100% mineral que contiene solo filtros físicos de óxido de zinc y dióxido de titanio.",
            "- Libre de parabenos, sin fragancia y no comedogénico.",
            "",
            "- Elegible para FSA y elegible para HSA"
          ],
          shortDescription: "Breve descripción del producto, enfocándose en sus características principales y beneficios clave para ofrecer una vista rápida de lo que el cliente puede esperar.",
          originalPrice: 200,
          color: "Negro",
          images: [
            "/Belleza/Maquillaje_58/vavalash_1.jpg",
            "/Belleza/Maquillaje_58/vavalash_2.jpg",
            "/Belleza/Maquillaje_58/vavalash_3.jpg",
            "/Belleza/Maquillaje_58/vavalash_4.jpg",
            "/Belleza/Maquillaje_58/vavalash_5.jpg",
            "/Belleza/Maquillaje_58/vavalash_6.jpg",
            "/Belleza/Maquillaje_58/vavalash_7.jpg",
          ],
          },
          {
            id: "21",
            name: "Maquinas De Obleas Lisa 16CM",
            price: 200.0,
            image: "/Cocina/MO lisa 16 cm.png",
            rating: 5,
            filter: "Electrodomésticos",
            category: "Cocina",
            fullDescription: [
          "Protector solar mineral tintado transparente:",
          "- Tinte universal para todos los tonos de piel.",
          "- Deja la piel con un brillo saludable al instante.",
          "- Compensa el yeso blanco típicamente asociado con los protectores solares minerales.",
          "- Ligero, sensación no grasa.",
          "",
          "Protector solar facial hidratante:",
          "- Formulado con niacinamida para calmar la piel.",
          "- Contiene ácido hialurónico para ayudar a retener la humedad natural de la piel.",
          "- Hidratante tintado con SPF 30.",
          "- Puede llevarse solo o debajo del maquillaje como una imprimación teñida con SPF 30.",
          "",
          "Adecuado para todo tipo de piel:",
          "- Incluyendo piel seca, sensible, grasa y propensa al acné.",
          "- No viene con un sello protector.",
          "",
          "Tres ceramidas esenciales:",
          "- Las ceramidas se encuentran naturalmente en la piel y pueden dañarse con la exposición al sol.",
          "- Todos los productos CeraVe están formulados con tres ceramidas esenciales (1, 3, 6-II) para ayudar a restaurar y mantener la barrera natural de la piel.",
          "",
          "Fórmula segura y suave:",
          "- Sin oxibenzona, sin avobenzona y sin benceno.",
          "- Protector solar 100% mineral que contiene solo filtros físicos de óxido de zinc y dióxido de titanio.",
          "- Libre de parabenos, sin fragancia y no comedogénico.",
          "",
          "- Elegible para FSA y elegible para HSA"
        ],
        shortDescription: "Breve descripción del producto, enfocándose en sus características principales y beneficios clave para ofrecer una vista rápida de lo que el cliente puede esperar.",
        originalPrice: 200,
        color: "Negro",
        images: [
          "/Belleza/Maquillaje_58/vavalash_1.jpg",
          "/Belleza/Maquillaje_58/vavalash_2.jpg",
          "/Belleza/Maquillaje_58/vavalash_3.jpg",
          "/Belleza/Maquillaje_58/vavalash_4.jpg",
          "/Belleza/Maquillaje_58/vavalash_5.jpg",
          "/Belleza/Maquillaje_58/vavalash_6.jpg",
          "/Belleza/Maquillaje_58/vavalash_7.jpg",
        ],
            
          },
    ],
    belleza:[
        {
          //SIEMPRE DEBE SER DIFERENTE DE ID ESTE VA HACER DE 40-60
          id: "40",
          name: "Maquillage",
          price: 20000,
          image: "/Belleza/MO lisa 16 cm.png",
          rating: 4,
          filter: "Maquillaje",
          category: "Belleza",
          fullDescription: [
            "Protector solar mineral tintado transparente:",
            "- Tinte universal para todos los tonos de piel.",
            "- Deja la piel con un brillo saludable al instante.",
            "- Compensa el yeso blanco típicamente asociado con los protectores solares minerales.",
            "- Ligero, sensación no grasa.",
            "",
            "Protector solar facial hidratante:",
            "- Formulado con niacinamida para calmar la piel.",
            "- Contiene ácido hialurónico para ayudar a retener la humedad natural de la piel.",
            "- Hidratante tintado con SPF 30.",
            "- Puede llevarse solo o debajo del maquillaje como una imprimación teñida con SPF 30.",
            "",
            "Adecuado para todo tipo de piel:",
            "- Incluyendo piel seca, sensible, grasa y propensa al acné.",
            "- No viene con un sello protector.",
            "",
            "Tres ceramidas esenciales:",
            "- Las ceramidas se encuentran naturalmente en la piel y pueden dañarse con la exposición al sol.",
            "- Todos los productos CeraVe están formulados con tres ceramidas esenciales (1, 3, 6-II) para ayudar a restaurar y mantener la barrera natural de la piel.",
            "",
            "Fórmula segura y suave:",
            "- Sin oxibenzona, sin avobenzona y sin benceno.",
            "- Protector solar 100% mineral que contiene solo filtros físicos de óxido de zinc y dióxido de titanio.",
            "- Libre de parabenos, sin fragancia y no comedogénico.",
            "",
            "- Elegible para FSA y elegible para HSA"
          ],
          shortDescription: "Breve descripción del producto, enfocándose en sus características principales y beneficios clave para ofrecer una vista rápida de lo que el cliente puede esperar.",
          originalPrice: 200,
          color: "Negro",
          images: [
            "/Belleza/Maquillaje_58/vavalash_1.jpg",
            "/Belleza/Maquillaje_58/vavalash_2.jpg",
            "/Belleza/Maquillaje_58/vavalash_3.jpg",
            "/Belleza/Maquillaje_58/vavalash_4.jpg",
            "/Belleza/Maquillaje_58/vavalash_5.jpg",
            "/Belleza/Maquillaje_58/vavalash_6.jpg",
            "/Belleza/Maquillaje_58/vavalash_7.jpg",
          ],
        },
    ],
    tecnologia: [
        {
           //SIEMPRE DEBE SER DIFERENTE DE ID ESTE VA HACER DE 1-19
            id: "1",
            name: "CCA CRA - Auriculares para monitor intraural IEM",
            price: 79900,
            image: "/Audifonos.png",
            rating: 5,
            filter: "Audífonos",
            category: "Tecnologia",
            fullDescription: [
              "Protector solar mineral tintado transparente:",
              "- Tinte universal para todos los tonos de piel.",
              "- Deja la piel con un brillo saludable al instante.",
              "- Compensa el yeso blanco típicamente asociado con los protectores solares minerales.",
              "- Ligero, sensación no grasa.",
              "",
              "Protector solar facial hidratante:",
              "- Formulado con niacinamida para calmar la piel.",
              "- Contiene ácido hialurónico para ayudar a retener la humedad natural de la piel.",
              "- Hidratante tintado con SPF 30.",
              "- Puede llevarse solo o debajo del maquillaje como una imprimación teñida con SPF 30.",
              "",
              "Adecuado para todo tipo de piel:",
              "- Incluyendo piel seca, sensible, grasa y propensa al acné.",
              "- No viene con un sello protector.",
              "",
              "Tres ceramidas esenciales:",
              "- Las ceramidas se encuentran naturalmente en la piel y pueden dañarse con la exposición al sol.",
              "- Todos los productos CeraVe están formulados con tres ceramidas esenciales (1, 3, 6-II) para ayudar a restaurar y mantener la barrera natural de la piel.",
              "",
              "Fórmula segura y suave:",
              "- Sin oxibenzona, sin avobenzona y sin benceno.",
              "- Protector solar 100% mineral que contiene solo filtros físicos de óxido de zinc y dióxido de titanio.",
              "- Libre de parabenos, sin fragancia y no comedogénico.",
              "",
              "- Elegible para FSA y elegible para HSA"
            ],
            shortDescription: "Breve descripción del producto, enfocándose en sus características principales y beneficios clave para ofrecer una vista rápida de lo que el cliente puede esperar.",
            originalPrice: 200,
            color: "Negro",
            images: [
              "/Belleza/Maquillaje_58/vavalash_1.jpg",
              "/Belleza/Maquillaje_58/vavalash_2.jpg",
              "/Belleza/Maquillaje_58/vavalash_3.jpg",
              "/Belleza/Maquillaje_58/vavalash_4.jpg",
              "/Belleza/Maquillaje_58/vavalash_5.jpg",
              "/Belleza/Maquillaje_58/vavalash_6.jpg",
              "/Belleza/Maquillaje_58/vavalash_7.jpg",
            ],
          },
        
          {
            id: "2",
            name: "Sceptre IPS - Monitor de 22 pulgadas 1080p 75Hz",
            price: 354500,
            image: "/Monitor1.png",
            rating: 5,
            filter: "Monitores",
            category: "Tecnologia",
            fullDescription: [
          "Protector solar mineral tintado transparente:",
          "- Tinte universal para todos los tonos de piel.",
          "- Deja la piel con un brillo saludable al instante.",
          "- Compensa el yeso blanco típicamente asociado con los protectores solares minerales.",
          "- Ligero, sensación no grasa.",
          "",
          "Protector solar facial hidratante:",
          "- Formulado con niacinamida para calmar la piel.",
          "- Contiene ácido hialurónico para ayudar a retener la humedad natural de la piel.",
          "- Hidratante tintado con SPF 30.",
          "- Puede llevarse solo o debajo del maquillaje como una imprimación teñida con SPF 30.",
          "",
          "Adecuado para todo tipo de piel:",
          "- Incluyendo piel seca, sensible, grasa y propensa al acné.",
          "- No viene con un sello protector.",
          "",
          "Tres ceramidas esenciales:",
          "- Las ceramidas se encuentran naturalmente en la piel y pueden dañarse con la exposición al sol.",
          "- Todos los productos CeraVe están formulados con tres ceramidas esenciales (1, 3, 6-II) para ayudar a restaurar y mantener la barrera natural de la piel.",
          "",
          "Fórmula segura y suave:",
          "- Sin oxibenzona, sin avobenzona y sin benceno.",
          "- Protector solar 100% mineral que contiene solo filtros físicos de óxido de zinc y dióxido de titanio.",
          "- Libre de parabenos, sin fragancia y no comedogénico.",
          "",
          "- Elegible para FSA y elegible para HSA"
        ],
        shortDescription: "Breve descripción del producto, enfocándose en sus características principales y beneficios clave para ofrecer una vista rápida de lo que el cliente puede esperar.",
        originalPrice: 200,
        color: "Negro",
        images: [
          "/Belleza/Maquillaje_58/vavalash_1.jpg",
          "/Belleza/Maquillaje_58/vavalash_2.jpg",
          "/Belleza/Maquillaje_58/vavalash_3.jpg",
          "/Belleza/Maquillaje_58/vavalash_4.jpg",
          "/Belleza/Maquillaje_58/vavalash_5.jpg",
          "/Belleza/Maquillaje_58/vavalash_6.jpg",
          "/Belleza/Maquillaje_58/vavalash_7.jpg",
        ],
            
          },
        
          {
            id: "3",
            name: "Acer Hub USB C, divisor USB C a HDMI",
            price: 75550,
            image: "/tecnologia/AcerHub.jpg",
            rating: 5,
            filter: "Accesorios",
            category: "Tecnologia",
            fullDescription: [
          "Protector solar mineral tintado transparente:",
          "- Tinte universal para todos los tonos de piel.",
          "- Deja la piel con un brillo saludable al instante.",
          "- Compensa el yeso blanco típicamente asociado con los protectores solares minerales.",
          "- Ligero, sensación no grasa.",
          "",
          "Protector solar facial hidratante:",
          "- Formulado con niacinamida para calmar la piel.",
          "- Contiene ácido hialurónico para ayudar a retener la humedad natural de la piel.",
          "- Hidratante tintado con SPF 30.",
          "- Puede llevarse solo o debajo del maquillaje como una imprimación teñida con SPF 30.",
          "",
          "Adecuado para todo tipo de piel:",
          "- Incluyendo piel seca, sensible, grasa y propensa al acné.",
          "- No viene con un sello protector.",
          "",
          "Tres ceramidas esenciales:",
          "- Las ceramidas se encuentran naturalmente en la piel y pueden dañarse con la exposición al sol.",
          "- Todos los productos CeraVe están formulados con tres ceramidas esenciales (1, 3, 6-II) para ayudar a restaurar y mantener la barrera natural de la piel.",
          "",
          "Fórmula segura y suave:",
          "- Sin oxibenzona, sin avobenzona y sin benceno.",
          "- Protector solar 100% mineral que contiene solo filtros físicos de óxido de zinc y dióxido de titanio.",
          "- Libre de parabenos, sin fragancia y no comedogénico.",
          "",
          "- Elegible para FSA y elegible para HSA"
        ],
        shortDescription: "Breve descripción del producto, enfocándose en sus características principales y beneficios clave para ofrecer una vista rápida de lo que el cliente puede esperar.",
        originalPrice: 200,
        color: "Negro",
        images: [
          "/Belleza/Maquillaje_58/vavalash_1.jpg",
          "/Belleza/Maquillaje_58/vavalash_2.jpg",
          "/Belleza/Maquillaje_58/vavalash_3.jpg",
          "/Belleza/Maquillaje_58/vavalash_4.jpg",
          "/Belleza/Maquillaje_58/vavalash_5.jpg",
          "/Belleza/Maquillaje_58/vavalash_6.jpg",
          "/Belleza/Maquillaje_58/vavalash_7.jpg",
        ],
            
          },
        
          {
            id: "4",
            name: "[Certificado Apple MFi] Paquete de 6 cargadores de iPhone (3/3/6/6/6/10 pies)",
            price: 41904,
            image: "/tecnologia/CablesCargadores.jpg",
            rating: 5,
            filter: "Accesorios",
            category: "Tecnologia",
            fullDescription: [
          "Protector solar mineral tintado transparente:",
          "- Tinte universal para todos los tonos de piel.",
          "- Deja la piel con un brillo saludable al instante.",
          "- Compensa el yeso blanco típicamente asociado con los protectores solares minerales.",
          "- Ligero, sensación no grasa.",
          "",
          "Protector solar facial hidratante:",
          "- Formulado con niacinamida para calmar la piel.",
          "- Contiene ácido hialurónico para ayudar a retener la humedad natural de la piel.",
          "- Hidratante tintado con SPF 30.",
          "- Puede llevarse solo o debajo del maquillaje como una imprimación teñida con SPF 30.",
          "",
          "Adecuado para todo tipo de piel:",
          "- Incluyendo piel seca, sensible, grasa y propensa al acné.",
          "- No viene con un sello protector.",
          "",
          "Tres ceramidas esenciales:",
          "- Las ceramidas se encuentran naturalmente en la piel y pueden dañarse con la exposición al sol.",
          "- Todos los productos CeraVe están formulados con tres ceramidas esenciales (1, 3, 6-II) para ayudar a restaurar y mantener la barrera natural de la piel.",
          "",
          "Fórmula segura y suave:",
          "- Sin oxibenzona, sin avobenzona y sin benceno.",
          "- Protector solar 100% mineral que contiene solo filtros físicos de óxido de zinc y dióxido de titanio.",
          "- Libre de parabenos, sin fragancia y no comedogénico.",
          "",
          "- Elegible para FSA y elegible para HSA"
        ],
        shortDescription: "Breve descripción del producto, enfocándose en sus características principales y beneficios clave para ofrecer una vista rápida de lo que el cliente puede esperar.",
        originalPrice: 200,
        color: "Negro",
        images: [
          "/Belleza/Maquillaje_58/vavalash_1.jpg",
          "/Belleza/Maquillaje_58/vavalash_2.jpg",
          "/Belleza/Maquillaje_58/vavalash_3.jpg",
          "/Belleza/Maquillaje_58/vavalash_4.jpg",
          "/Belleza/Maquillaje_58/vavalash_5.jpg",
          "/Belleza/Maquillaje_58/vavalash_6.jpg",
          "/Belleza/Maquillaje_58/vavalash_7.jpg",
        ],
            
          },
        
          {
            id: "5",
            name: "Sceptre LED - Monitor de 22 pulgadas 1080p 75Hz",
            price: 75550,
            image: "/tecnologia/MonitorLED.jpg",
            rating: 5,
            filter: "Monitores",
            category: "Tecnologia",
            fullDescription: [
          "Protector solar mineral tintado transparente:",
          "- Tinte universal para todos los tonos de piel.",
          "- Deja la piel con un brillo saludable al instante.",
          "- Compensa el yeso blanco típicamente asociado con los protectores solares minerales.",
          "- Ligero, sensación no grasa.",
          "",
          "Protector solar facial hidratante:",
          "- Formulado con niacinamida para calmar la piel.",
          "- Contiene ácido hialurónico para ayudar a retener la humedad natural de la piel.",
          "- Hidratante tintado con SPF 30.",
          "- Puede llevarse solo o debajo del maquillaje como una imprimación teñida con SPF 30.",
          "",
          "Adecuado para todo tipo de piel:",
          "- Incluyendo piel seca, sensible, grasa y propensa al acné.",
          "- No viene con un sello protector.",
          "",
          "Tres ceramidas esenciales:",
          "- Las ceramidas se encuentran naturalmente en la piel y pueden dañarse con la exposición al sol.",
          "- Todos los productos CeraVe están formulados con tres ceramidas esenciales (1, 3, 6-II) para ayudar a restaurar y mantener la barrera natural de la piel.",
          "",
          "Fórmula segura y suave:",
          "- Sin oxibenzona, sin avobenzona y sin benceno.",
          "- Protector solar 100% mineral que contiene solo filtros físicos de óxido de zinc y dióxido de titanio.",
          "- Libre de parabenos, sin fragancia y no comedogénico.",
          "",
          "- Elegible para FSA y elegible para HSA"
        ],
        shortDescription: "Breve descripción del producto, enfocándose en sus características principales y beneficios clave para ofrecer una vista rápida de lo que el cliente puede esperar.",
        originalPrice: 200,
        color: "Negro",
        images: [
          "/Belleza/Maquillaje_58/vavalash_1.jpg",
          "/Belleza/Maquillaje_58/vavalash_2.jpg",
          "/Belleza/Maquillaje_58/vavalash_3.jpg",
          "/Belleza/Maquillaje_58/vavalash_4.jpg",
          "/Belleza/Maquillaje_58/vavalash_5.jpg",
          "/Belleza/Maquillaje_58/vavalash_6.jpg",
          "/Belleza/Maquillaje_58/vavalash_7.jpg",
        ],
            
          },
        
          {
            id: "6",
            name: " TRIGKEY Mini PC Ryzen 7 W11 Pro Desktop",
            price: 1295400,
            image: "/Mini_PC.png",
            rating: 5,
            filter: "Computadores",
            category: "Tecnologia",
            fullDescription: [
          "Protector solar mineral tintado transparente:",
          "- Tinte universal para todos los tonos de piel.",
          "- Deja la piel con un brillo saludable al instante.",
          "- Compensa el yeso blanco típicamente asociado con los protectores solares minerales.",
          "- Ligero, sensación no grasa.",
          "",
          "Protector solar facial hidratante:",
          "- Formulado con niacinamida para calmar la piel.",
          "- Contiene ácido hialurónico para ayudar a retener la humedad natural de la piel.",
          "- Hidratante tintado con SPF 30.",
          "- Puede llevarse solo o debajo del maquillaje como una imprimación teñida con SPF 30.",
          "",
          "Adecuado para todo tipo de piel:",
          "- Incluyendo piel seca, sensible, grasa y propensa al acné.",
          "- No viene con un sello protector.",
          "",
          "Tres ceramidas esenciales:",
          "- Las ceramidas se encuentran naturalmente en la piel y pueden dañarse con la exposición al sol.",
          "- Todos los productos CeraVe están formulados con tres ceramidas esenciales (1, 3, 6-II) para ayudar a restaurar y mantener la barrera natural de la piel.",
          "",
          "Fórmula segura y suave:",
          "- Sin oxibenzona, sin avobenzona y sin benceno.",
          "- Protector solar 100% mineral que contiene solo filtros físicos de óxido de zinc y dióxido de titanio.",
          "- Libre de parabenos, sin fragancia y no comedogénico.",
          "",
          "- Elegible para FSA y elegible para HSA"
        ],
        shortDescription: "Breve descripción del producto, enfocándose en sus características principales y beneficios clave para ofrecer una vista rápida de lo que el cliente puede esperar.",
        originalPrice: 200,
        color: "Negro",
        images: [
          "/Belleza/Maquillaje_58/vavalash_1.jpg",
          "/Belleza/Maquillaje_58/vavalash_2.jpg",
          "/Belleza/Maquillaje_58/vavalash_3.jpg",
          "/Belleza/Maquillaje_58/vavalash_4.jpg",
          "/Belleza/Maquillaje_58/vavalash_5.jpg",
          "/Belleza/Maquillaje_58/vavalash_6.jpg",
          "/Belleza/Maquillaje_58/vavalash_7.jpg",
        ],
            
          },
        
          {
            id: "7",
            name: "Auriculares inalámbricos Bluetooth V5.3, reproducción de 50 horas",
            price: 79990,
            image: "/tecnologia/Audifonos2.jpg",
            rating: 5,
            filter: "Audífonos",
            category: "Tecnologia",
            fullDescription: [
          "Protector solar mineral tintado transparente:",
          "- Tinte universal para todos los tonos de piel.",
          "- Deja la piel con un brillo saludable al instante.",
          "- Compensa el yeso blanco típicamente asociado con los protectores solares minerales.",
          "- Ligero, sensación no grasa.",
          "",
          "Protector solar facial hidratante:",
          "- Formulado con niacinamida para calmar la piel.",
          "- Contiene ácido hialurónico para ayudar a retener la humedad natural de la piel.",
          "- Hidratante tintado con SPF 30.",
          "- Puede llevarse solo o debajo del maquillaje como una imprimación teñida con SPF 30.",
          "",
          "Adecuado para todo tipo de piel:",
          "- Incluyendo piel seca, sensible, grasa y propensa al acné.",
          "- No viene con un sello protector.",
          "",
          "Tres ceramidas esenciales:",
          "- Las ceramidas se encuentran naturalmente en la piel y pueden dañarse con la exposición al sol.",
          "- Todos los productos CeraVe están formulados con tres ceramidas esenciales (1, 3, 6-II) para ayudar a restaurar y mantener la barrera natural de la piel.",
          "",
          "Fórmula segura y suave:",
          "- Sin oxibenzona, sin avobenzona y sin benceno.",
          "- Protector solar 100% mineral que contiene solo filtros físicos de óxido de zinc y dióxido de titanio.",
          "- Libre de parabenos, sin fragancia y no comedogénico.",
          "",
          "- Elegible para FSA y elegible para HSA"
        ],
        shortDescription: "Breve descripción del producto, enfocándose en sus características principales y beneficios clave para ofrecer una vista rápida de lo que el cliente puede esperar.",
        originalPrice: 200,
        color: "Negro",
        images: [
          "/Belleza/Maquillaje_58/vavalash_1.jpg",
          "/Belleza/Maquillaje_58/vavalash_2.jpg",
          "/Belleza/Maquillaje_58/vavalash_3.jpg",
          "/Belleza/Maquillaje_58/vavalash_4.jpg",
          "/Belleza/Maquillaje_58/vavalash_5.jpg",
          "/Belleza/Maquillaje_58/vavalash_6.jpg",
          "/Belleza/Maquillaje_58/vavalash_7.jpg",
        ],
            
          },
        
          {
            id: "8",
            name: "UGREEN Revodok USB C Hub 5 en 1 ",
            price: 79990,
            image: "/tecnologia/USBHUB.jpg",
            rating: 5,
            filter: "Accesorios",
            category: "Tecnologia",
            fullDescription: [
          "Protector solar mineral tintado transparente:",
          "- Tinte universal para todos los tonos de piel.",
          "- Deja la piel con un brillo saludable al instante.",
          "- Compensa el yeso blanco típicamente asociado con los protectores solares minerales.",
          "- Ligero, sensación no grasa.",
          "",
          "Protector solar facial hidratante:",
          "- Formulado con niacinamida para calmar la piel.",
          "- Contiene ácido hialurónico para ayudar a retener la humedad natural de la piel.",
          "- Hidratante tintado con SPF 30.",
          "- Puede llevarse solo o debajo del maquillaje como una imprimación teñida con SPF 30.",
          "",
          "Adecuado para todo tipo de piel:",
          "- Incluyendo piel seca, sensible, grasa y propensa al acné.",
          "- No viene con un sello protector.",
          "",
          "Tres ceramidas esenciales:",
          "- Las ceramidas se encuentran naturalmente en la piel y pueden dañarse con la exposición al sol.",
          "- Todos los productos CeraVe están formulados con tres ceramidas esenciales (1, 3, 6-II) para ayudar a restaurar y mantener la barrera natural de la piel.",
          "",
          "Fórmula segura y suave:",
          "- Sin oxibenzona, sin avobenzona y sin benceno.",
          "- Protector solar 100% mineral que contiene solo filtros físicos de óxido de zinc y dióxido de titanio.",
          "- Libre de parabenos, sin fragancia y no comedogénico.",
          "",
          "- Elegible para FSA y elegible para HSA"
        ],
        shortDescription: "Breve descripción del producto, enfocándose en sus características principales y beneficios clave para ofrecer una vista rápida de lo que el cliente puede esperar.",
        originalPrice: 200,
        color: "Negro",
        images: [
          "/Belleza/Maquillaje_58/vavalash_1.jpg",
          "/Belleza/Maquillaje_58/vavalash_2.jpg",
          "/Belleza/Maquillaje_58/vavalash_3.jpg",
          "/Belleza/Maquillaje_58/vavalash_4.jpg",
          "/Belleza/Maquillaje_58/vavalash_5.jpg",
          "/Belleza/Maquillaje_58/vavalash_6.jpg",
          "/Belleza/Maquillaje_58/vavalash_7.jpg",
        ],
            
          },
        
          {
            id: "9",
            name: "Beelink Mini PC S12 Pro",
            price: 79990,
            image: "/tecnologia/Mini_PCINTEL.jpg",
            rating: 5,
            filter: "Computadores",
            category: "Tecnologia",
            fullDescription: [
          "Protector solar mineral tintado transparente:",
          "- Tinte universal para todos los tonos de piel.",
          "- Deja la piel con un brillo saludable al instante.",
          "- Compensa el yeso blanco típicamente asociado con los protectores solares minerales.",
          "- Ligero, sensación no grasa.",
          "",
          "Protector solar facial hidratante:",
          "- Formulado con niacinamida para calmar la piel.",
          "- Contiene ácido hialurónico para ayudar a retener la humedad natural de la piel.",
          "- Hidratante tintado con SPF 30.",
          "- Puede llevarse solo o debajo del maquillaje como una imprimación teñida con SPF 30.",
          "",
          "Adecuado para todo tipo de piel:",
          "- Incluyendo piel seca, sensible, grasa y propensa al acné.",
          "- No viene con un sello protector.",
          "",
          "Tres ceramidas esenciales:",
          "- Las ceramidas se encuentran naturalmente en la piel y pueden dañarse con la exposición al sol.",
          "- Todos los productos CeraVe están formulados con tres ceramidas esenciales (1, 3, 6-II) para ayudar a restaurar y mantener la barrera natural de la piel.",
          "",
          "Fórmula segura y suave:",
          "- Sin oxibenzona, sin avobenzona y sin benceno.",
          "- Protector solar 100% mineral que contiene solo filtros físicos de óxido de zinc y dióxido de titanio.",
          "- Libre de parabenos, sin fragancia y no comedogénico.",
          "",
          "- Elegible para FSA y elegible para HSA"
        ],
        shortDescription: "Breve descripción del producto, enfocándose en sus características principales y beneficios clave para ofrecer una vista rápida de lo que el cliente puede esperar.",
        originalPrice: 200,
        color: "Negro",
        images: [
          "/Belleza/Maquillaje_58/vavalash_1.jpg",
          "/Belleza/Maquillaje_58/vavalash_2.jpg",
          "/Belleza/Maquillaje_58/vavalash_3.jpg",
          "/Belleza/Maquillaje_58/vavalash_4.jpg",
          "/Belleza/Maquillaje_58/vavalash_5.jpg",
          "/Belleza/Maquillaje_58/vavalash_6.jpg",
          "/Belleza/Maquillaje_58/vavalash_7.jpg",
        ],
            
          },
        
          {
            id: "10",
            name: "Auriculares inalámbricos Bluetooth V5.3, reproducción de 50 horas",
            price: 79990,
            image: "/tecnologia/Audifonos2.jpg",
            rating: 5,
            filter: "Audífonos",
            category: "Tecnologia",
            fullDescription: [
          "Protector solar mineral tintado transparente:",
          "- Tinte universal para todos los tonos de piel.",
          "- Deja la piel con un brillo saludable al instante.",
          "- Compensa el yeso blanco típicamente asociado con los protectores solares minerales.",
          "- Ligero, sensación no grasa.",
          "",
          "Protector solar facial hidratante:",
          "- Formulado con niacinamida para calmar la piel.",
          "- Contiene ácido hialurónico para ayudar a retener la humedad natural de la piel.",
          "- Hidratante tintado con SPF 30.",
          "- Puede llevarse solo o debajo del maquillaje como una imprimación teñida con SPF 30.",
          "",
          "Adecuado para todo tipo de piel:",
          "- Incluyendo piel seca, sensible, grasa y propensa al acné.",
          "- No viene con un sello protector.",
          "",
          "Tres ceramidas esenciales:",
          "- Las ceramidas se encuentran naturalmente en la piel y pueden dañarse con la exposición al sol.",
          "- Todos los productos CeraVe están formulados con tres ceramidas esenciales (1, 3, 6-II) para ayudar a restaurar y mantener la barrera natural de la piel.",
          "",
          "Fórmula segura y suave:",
          "- Sin oxibenzona, sin avobenzona y sin benceno.",
          "- Protector solar 100% mineral que contiene solo filtros físicos de óxido de zinc y dióxido de titanio.",
          "- Libre de parabenos, sin fragancia y no comedogénico.",
          "",
          "- Elegible para FSA y elegible para HSA"
        ],
        shortDescription: "Breve descripción del producto, enfocándose en sus características principales y beneficios clave para ofrecer una vista rápida de lo que el cliente puede esperar.",
        originalPrice: 200,
        color: "Negro",
        images: [
          "/Belleza/Maquillaje_58/vavalash_1.jpg",
          "/Belleza/Maquillaje_58/vavalash_2.jpg",
          "/Belleza/Maquillaje_58/vavalash_3.jpg",
          "/Belleza/Maquillaje_58/vavalash_4.jpg",
          "/Belleza/Maquillaje_58/vavalash_5.jpg",
          "/Belleza/Maquillaje_58/vavalash_6.jpg",
          "/Belleza/Maquillaje_58/vavalash_7.jpg",
        ],
            
          },
        
          {
            id: "11",
            name: "Spray limpiador de pantalla (16 onzas)",
            price: 47990,
            image: "/tecnologia/limpiadorpantalla.jpg",
            rating: 5,
            filter: "Audífonos",
            category: "Tecnologia",
            fullDescription: [
          "Protector solar mineral tintado transparente:",
          "- Tinte universal para todos los tonos de piel.",
          "- Deja la piel con un brillo saludable al instante.",
          "- Compensa el yeso blanco típicamente asociado con los protectores solares minerales.",
          "- Ligero, sensación no grasa.",
          "",
          "Protector solar facial hidratante:",
          "- Formulado con niacinamida para calmar la piel.",
          "- Contiene ácido hialurónico para ayudar a retener la humedad natural de la piel.",
          "- Hidratante tintado con SPF 30.",
          "- Puede llevarse solo o debajo del maquillaje como una imprimación teñida con SPF 30.",
          "",
          "Adecuado para todo tipo de piel:",
          "- Incluyendo piel seca, sensible, grasa y propensa al acné.",
          "- No viene con un sello protector.",
          "",
          "Tres ceramidas esenciales:",
          "- Las ceramidas se encuentran naturalmente en la piel y pueden dañarse con la exposición al sol.",
          "- Todos los productos CeraVe están formulados con tres ceramidas esenciales (1, 3, 6-II) para ayudar a restaurar y mantener la barrera natural de la piel.",
          "",
          "Fórmula segura y suave:",
          "- Sin oxibenzona, sin avobenzona y sin benceno.",
          "- Protector solar 100% mineral que contiene solo filtros físicos de óxido de zinc y dióxido de titanio.",
          "- Libre de parabenos, sin fragancia y no comedogénico.",
          "",
          "- Elegible para FSA y elegible para HSA"
        ],
        shortDescription: "Breve descripción del producto, enfocándose en sus características principales y beneficios clave para ofrecer una vista rápida de lo que el cliente puede esperar.",
        originalPrice: 200,
        color: "Negro",
        images: [
          "/Belleza/Maquillaje_58/vavalash_1.jpg",
          "/Belleza/Maquillaje_58/vavalash_2.jpg",
          "/Belleza/Maquillaje_58/vavalash_3.jpg",
          "/Belleza/Maquillaje_58/vavalash_4.jpg",
          "/Belleza/Maquillaje_58/vavalash_5.jpg",
          "/Belleza/Maquillaje_58/vavalash_6.jpg",
          "/Belleza/Maquillaje_58/vavalash_7.jpg",
        ],
            
          },
        
          {
            id: "12",
            name: "Auriculares inalámbricos Bluetooth V5.3, reproducción de 50 horas",
            price: 79990,
            image: "/tecnologia/Audifonos2.jpg",
            rating: 5,
            filter: "Audífonos",
            category: "Tecnologia",
            fullDescription: [
          "Protector solar mineral tintado transparente:",
          "- Tinte universal para todos los tonos de piel.",
          "- Deja la piel con un brillo saludable al instante.",
          "- Compensa el yeso blanco típicamente asociado con los protectores solares minerales.",
          "- Ligero, sensación no grasa.",
          "",
          "Protector solar facial hidratante:",
          "- Formulado con niacinamida para calmar la piel.",
          "- Contiene ácido hialurónico para ayudar a retener la humedad natural de la piel.",
          "- Hidratante tintado con SPF 30.",
          "- Puede llevarse solo o debajo del maquillaje como una imprimación teñida con SPF 30.",
          "",
          "Adecuado para todo tipo de piel:",
          "- Incluyendo piel seca, sensible, grasa y propensa al acné.",
          "- No viene con un sello protector.",
          "",
          "Tres ceramidas esenciales:",
          "- Las ceramidas se encuentran naturalmente en la piel y pueden dañarse con la exposición al sol.",
          "- Todos los productos CeraVe están formulados con tres ceramidas esenciales (1, 3, 6-II) para ayudar a restaurar y mantener la barrera natural de la piel.",
          "",
          "Fórmula segura y suave:",
          "- Sin oxibenzona, sin avobenzona y sin benceno.",
          "- Protector solar 100% mineral que contiene solo filtros físicos de óxido de zinc y dióxido de titanio.",
          "- Libre de parabenos, sin fragancia y no comedogénico.",
          "",
          "- Elegible para FSA y elegible para HSA"
        ],
        shortDescription: "Breve descripción del producto, enfocándose en sus características principales y beneficios clave para ofrecer una vista rápida de lo que el cliente puede esperar.",
        originalPrice: 200,
        color: "Negro",
        images: [
          "/Belleza/Maquillaje_58/vavalash_1.jpg",
          "/Belleza/Maquillaje_58/vavalash_2.jpg",
          "/Belleza/Maquillaje_58/vavalash_3.jpg",
          "/Belleza/Maquillaje_58/vavalash_4.jpg",
          "/Belleza/Maquillaje_58/vavalash_5.jpg",
          "/Belleza/Maquillaje_58/vavalash_6.jpg",
          "/Belleza/Maquillaje_58/vavalash_7.jpg",
        ],
            
          },
    ],
    // Puedes agregar más categorías de productos si las tienes.
    deporte: [
      {
        id: "40",
        name: "Crema CeraVe Protector solar tintado con SPF 30",
        price: 79900,
        image: "/Belleza/Crema_40/CeraVeSunscreen_1.jpg",
        rating: 5,
        filter: "Protectores Solares",
        category: "Belleza",
        fullDescription: [
          "Protector solar mineral tintado transparente:",
          "- Tinte universal para todos los tonos de piel.",
          "- Deja la piel con un brillo saludable al instante.",
          "- Compensa el yeso blanco típicamente asociado con los protectores solares minerales.",
          "- Ligero, sensación no grasa.",
          "",
          "Protector solar facial hidratante:",
          "- Formulado con niacinamida para calmar la piel.",
          "- Contiene ácido hialurónico para ayudar a retener la humedad natural de la piel.",
          "- Hidratante tintado con SPF 30.",
          "- Puede llevarse solo o debajo del maquillaje como una imprimación teñida con SPF 30.",
          "",
          "Adecuado para todo tipo de piel:",
          "- Incluyendo piel seca, sensible, grasa y propensa al acné.",
          "- No viene con un sello protector.",
          "",
          "Tres ceramidas esenciales:",
          "- Las ceramidas se encuentran naturalmente en la piel y pueden dañarse con la exposición al sol.",
          "- Todos los productos CeraVe están formulados con tres ceramidas esenciales (1, 3, 6-II) para ayudar a restaurar y mantener la barrera natural de la piel.",
          "",
          "Fórmula segura y suave:",
          "- Sin oxibenzona, sin avobenzona y sin benceno.",
          "- Protector solar 100% mineral que contiene solo filtros físicos de óxido de zinc y dióxido de titanio.",
          "- Libre de parabenos, sin fragancia y no comedogénico.",
          "",
          "- Elegible para FSA y elegible para HSA"
        ],
        shortDescription: "Breve descripción del producto, enfocándose en sus características principales y beneficios clave para ofrecer una vista rápida de lo que el cliente puede esperar.",
        originalPrice: 200,
        color: "Negro",
        images: [
          "/Belleza/Crema_46/CeraVeSunscreen_1.jpg",
          "/Belleza/Crema_46/CeraVeSunscreen_2.jpg",
          "/Belleza/Crema_46/CeraVeSunscreen_3.jpg",
          "/Belleza/Crema_46/CeraVeSunscreen_4.jpg",
          "/Belleza/Crema_46/CeraVeSunscreen_5.jpg",
          "/Belleza/Crema_46/CeraVeSunscreen_6.jpg"
        ],
      },

      {
        id: "41",
        name: "Crema Limpiadora Facial hidratante CeraVe, 473 ML ",
        price: 79900,
        image: "/Belleza/Crema_41/CeraVeCleanser_1.jpg",
        rating: 5,
        filter: "Limpiadores",
        category: "Belleza",
        fullDescription: [
          "Protector solar mineral tintado transparente:",
          "- Tinte universal para todos los tonos de piel.",
          "- Deja la piel con un brillo saludable al instante.",
          "- Compensa el yeso blanco típicamente asociado con los protectores solares minerales.",
          "- Ligero, sensación no grasa.",
          "",
          "Protector solar facial hidratante:",
          "- Formulado con niacinamida para calmar la piel.",
          "- Contiene ácido hialurónico para ayudar a retener la humedad natural de la piel.",
          "- Hidratante tintado con SPF 30.",
          "- Puede llevarse solo o debajo del maquillaje como una imprimación teñida con SPF 30.",
          "",
          "Adecuado para todo tipo de piel:",
          "- Incluyendo piel seca, sensible, grasa y propensa al acné.",
          "- No viene con un sello protector.",
          "",
          "Tres ceramidas esenciales:",
          "- Las ceramidas se encuentran naturalmente en la piel y pueden dañarse con la exposición al sol.",
          "- Todos los productos CeraVe están formulados con tres ceramidas esenciales (1, 3, 6-II) para ayudar a restaurar y mantener la barrera natural de la piel.",
          "",
          "Fórmula segura y suave:",
          "- Sin oxibenzona, sin avobenzona y sin benceno.",
          "- Protector solar 100% mineral que contiene solo filtros físicos de óxido de zinc y dióxido de titanio.",
          "- Libre de parabenos, sin fragancia y no comedogénico.",
          "",
          "- Elegible para FSA y elegible para HSA"
        ],
        shortDescription: "Breve descripción del producto, enfocándose en sus características principales y beneficios clave para ofrecer una vista rápida de lo que el cliente puede esperar.",
        originalPrice: 200,
        color: "Negro",
        images: [
          "/Belleza/Crema_41/CeraVeCleanser_1.jpg",
          "/Belleza/Crema_41/CeraVeCleanser_2.jpg",
          "/Belleza/Crema_41/CeraVeCleanser_3.jpg",
          "/Belleza/Crema_41/CeraVeCleanser_4.jpg",
          "/Belleza/Crema_41/CeraVeCleanser_5.jpg",
          "/Belleza/Crema_41/CeraVeCleanser_6.jpg"
        ],
      },
    
      
      {
        id: "42",
        name: "Maquillaje NYX PROFESSIONAL MAKEUP, delineador líquido impermeable, fórmula vegana",
        price: 79900,
        image: "/Belleza/Maquillaje_42/NYX_1.jpg",
        rating: 5,
        filter: "Maquillaje",
        category: "Belleza",
        fullDescription: [
          "Protector solar mineral tintado transparente:",
          "- Tinte universal para todos los tonos de piel.",
          "- Deja la piel con un brillo saludable al instante.",
          "- Compensa el yeso blanco típicamente asociado con los protectores solares minerales.",
          "- Ligero, sensación no grasa.",
          "",
          "Protector solar facial hidratante:",
          "- Formulado con niacinamida para calmar la piel.",
          "- Contiene ácido hialurónico para ayudar a retener la humedad natural de la piel.",
          "- Hidratante tintado con SPF 30.",
          "- Puede llevarse solo o debajo del maquillaje como una imprimación teñida con SPF 30.",
          "",
          "Adecuado para todo tipo de piel:",
          "- Incluyendo piel seca, sensible, grasa y propensa al acné.",
          "- No viene con un sello protector.",
          "",
          "Tres ceramidas esenciales:",
          "- Las ceramidas se encuentran naturalmente en la piel y pueden dañarse con la exposición al sol.",
          "- Todos los productos CeraVe están formulados con tres ceramidas esenciales (1, 3, 6-II) para ayudar a restaurar y mantener la barrera natural de la piel.",
          "",
          "Fórmula segura y suave:",
          "- Sin oxibenzona, sin avobenzona y sin benceno.",
          "- Protector solar 100% mineral que contiene solo filtros físicos de óxido de zinc y dióxido de titanio.",
          "- Libre de parabenos, sin fragancia y no comedogénico.",
          "",
          "- Elegible para FSA y elegible para HSA"
        ],
        shortDescription: "Breve descripción del producto, enfocándose en sus características principales y beneficios clave para ofrecer una vista rápida de lo que el cliente puede esperar.",
        originalPrice: 200,
        color: "Negro",
        images: [
          "/Belleza/Maquillaje_42/NYX_1.jpg",
          "/Belleza/Maquillaje_42/NYX_2.jpg",
          "/Belleza/Maquillaje_42/NYX_3.jpg",
          "/Belleza/Maquillaje_42/NYX_4.jpg",
        ],
      },
      
      {
        id: "43",
        name: "Crema CeraVe Hidratante facial y corporal diaria para pieles secas, Paquete de Dos Cremas de 539 gramos",
        price: 79900,
        image: "/Belleza/Crema_43/CeraVeHidratanteFacial_1.jpg",
        rating: 5,
        filter: "Cremas Humectantes",
        category: "Belleza",
        fullDescription: [
          "Protector solar mineral tintado transparente:",
          "- Tinte universal para todos los tonos de piel.",
          "- Deja la piel con un brillo saludable al instante.",
          "- Compensa el yeso blanco típicamente asociado con los protectores solares minerales.",
          "- Ligero, sensación no grasa.",
          "",
          "Protector solar facial hidratante:",
          "- Formulado con niacinamida para calmar la piel.",
          "- Contiene ácido hialurónico para ayudar a retener la humedad natural de la piel.",
          "- Hidratante tintado con SPF 30.",
          "- Puede llevarse solo o debajo del maquillaje como una imprimación teñida con SPF 30.",
          "",
          "Adecuado para todo tipo de piel:",
          "- Incluyendo piel seca, sensible, grasa y propensa al acné.",
          "- No viene con un sello protector.",
          "",
          "Tres ceramidas esenciales:",
          "- Las ceramidas se encuentran naturalmente en la piel y pueden dañarse con la exposición al sol.",
          "- Todos los productos CeraVe están formulados con tres ceramidas esenciales (1, 3, 6-II) para ayudar a restaurar y mantener la barrera natural de la piel.",
          "",
          "Fórmula segura y suave:",
          "- Sin oxibenzona, sin avobenzona y sin benceno.",
          "- Protector solar 100% mineral que contiene solo filtros físicos de óxido de zinc y dióxido de titanio.",
          "- Libre de parabenos, sin fragancia y no comedogénico.",
          "",
          "- Elegible para FSA y elegible para HSA"
        ],
        shortDescription: "Breve descripción del producto, enfocándose en sus características principales y beneficios clave para ofrecer una vista rápida de lo que el cliente puede esperar.",
        originalPrice: 200,
        color: "Negro",
        images: [
          "/Belleza/Crema_43/CeraVeHidratanteFacial_1.jpg",
          "/Belleza/Crema_43/CeraVeHidratanteFacial_2.jpg",
          "/Belleza/Crema_43/CeraVeHidratanteFacial_3.jpg",
          "/Belleza/Crema_43/CeraVeHidratanteFacial_4.jpg",
          "/Belleza/Crema_43/CeraVeHidratanteFacial_5.jpg",
          "/Belleza/Crema_43/CeraVeHidratanteFacial_6.jpg",
        ],
      },

      {
        id: "44",
        name: "Maquillaje Prism Makeup paleta de sombra",
        price: 79900,
        image: "/Belleza/Maquillaje_44/PaletaPrismMakeUp_1.jpg",
        rating: 5,
        filter: "Maquillaje",
        category: "Belleza",
        fullDescription: [
          "Protector solar mineral tintado transparente:",
          "- Tinte universal para todos los tonos de piel.",
          "- Deja la piel con un brillo saludable al instante.",
          "- Compensa el yeso blanco típicamente asociado con los protectores solares minerales.",
          "- Ligero, sensación no grasa.",
          "",
          "Protector solar facial hidratante:",
          "- Formulado con niacinamida para calmar la piel.",
          "- Contiene ácido hialurónico para ayudar a retener la humedad natural de la piel.",
          "- Hidratante tintado con SPF 30.",
          "- Puede llevarse solo o debajo del maquillaje como una imprimación teñida con SPF 30.",
          "",
          "Adecuado para todo tipo de piel:",
          "- Incluyendo piel seca, sensible, grasa y propensa al acné.",
          "- No viene con un sello protector.",
          "",
          "Tres ceramidas esenciales:",
          "- Las ceramidas se encuentran naturalmente en la piel y pueden dañarse con la exposición al sol.",
          "- Todos los productos CeraVe están formulados con tres ceramidas esenciales (1, 3, 6-II) para ayudar a restaurar y mantener la barrera natural de la piel.",
          "",
          "Fórmula segura y suave:",
          "- Sin oxibenzona, sin avobenzona y sin benceno.",
          "- Protector solar 100% mineral que contiene solo filtros físicos de óxido de zinc y dióxido de titanio.",
          "- Libre de parabenos, sin fragancia y no comedogénico.",
          "",
          "- Elegible para FSA y elegible para HSA"
        ],
        shortDescription: "Breve descripción del producto, enfocándose en sus características principales y beneficios clave para ofrecer una vista rápida de lo que el cliente puede esperar.",
        originalPrice: 200,
        color: "Negro",
        images: [
          "/Belleza/Maquillaje_44/PaletaPrismMakeUp_1.jpg",
          "/Belleza/Maquillaje_44/PaletaPrismMakeUp_2.jpg",
          "/Belleza/Maquillaje_44/PaletaPrismMakeUp_3.jpg",
          "/Belleza/Maquillaje_44/PaletaPrismMakeUp_4.jpg",
          "/Belleza/Maquillaje_44/PaletaPrismMakeUp_5.jpg",
          "/Belleza/Maquillaje_44/PaletaPrismMakeUp_6.jpg",
          "/Belleza/Maquillaje_44/PaletaPrismMakeUp_7.jpg",
        ],
      },

      {
        id: "45",
        name: "Crema CeraVe Loción hidratante facial de 89 Mililitro",
        price: 79900,
        image: "/Belleza/Crema_45/CeraVePMFacial_1.jpg",
        rating: 5,
        filter: "Cremas Humectantes",
        category: "Belleza",
        fullDescription: [
          "Protector solar mineral tintado transparente:",
          "- Tinte universal para todos los tonos de piel.",
          "- Deja la piel con un brillo saludable al instante.",
          "- Compensa el yeso blanco típicamente asociado con los protectores solares minerales.",
          "- Ligero, sensación no grasa.",
          "",
          "Protector solar facial hidratante:",
          "- Formulado con niacinamida para calmar la piel.",
          "- Contiene ácido hialurónico para ayudar a retener la humedad natural de la piel.",
          "- Hidratante tintado con SPF 30.",
          "- Puede llevarse solo o debajo del maquillaje como una imprimación teñida con SPF 30.",
          "",
          "Adecuado para todo tipo de piel:",
          "- Incluyendo piel seca, sensible, grasa y propensa al acné.",
          "- No viene con un sello protector.",
          "",
          "Tres ceramidas esenciales:",
          "- Las ceramidas se encuentran naturalmente en la piel y pueden dañarse con la exposición al sol.",
          "- Todos los productos CeraVe están formulados con tres ceramidas esenciales (1, 3, 6-II) para ayudar a restaurar y mantener la barrera natural de la piel.",
          "",
          "Fórmula segura y suave:",
          "- Sin oxibenzona, sin avobenzona y sin benceno.",
          "- Protector solar 100% mineral que contiene solo filtros físicos de óxido de zinc y dióxido de titanio.",
          "- Libre de parabenos, sin fragancia y no comedogénico.",
          "",
          "- Elegible para FSA y elegible para HSA"
        ],
        shortDescription: "Breve descripción del producto, enfocándose en sus características principales y beneficios clave para ofrecer una vista rápida de lo que el cliente puede esperar.",
        originalPrice: 200,
        color: "Negro",
        images: [
          "/Belleza/Crema_45/CeraVePMFacial_1.jpg",
          "/Belleza/Crema_45/CeraVePMFacial_2.jpg",
          "/Belleza/Crema_45/CeraVePMFacial_3.jpg",
          "/Belleza/Crema_45/CeraVePMFacial_4.jpg",
          "/Belleza/Crema_45/CeraVePMFacial_5.jpg",
          "/Belleza/Crema_45/CeraVePMFacial_6.jpg",
        ],
      },

      {
        id: "46",
        name: "Maquillaje e.l.f., Lápiz para levantamiento de cejas instantáneo",
        price: 79900,
        image: "/Belleza/Maquillaje_46/e.l.f._1.jpg",
        rating: 5,
        filter: "Maquillaje",
        category: "Belleza",
        fullDescription: [
          "Protector solar mineral tintado transparente:",
          "- Tinte universal para todos los tonos de piel.",
          "- Deja la piel con un brillo saludable al instante.",
          "- Compensa el yeso blanco típicamente asociado con los protectores solares minerales.",
          "- Ligero, sensación no grasa.",
          "",
          "Protector solar facial hidratante:",
          "- Formulado con niacinamida para calmar la piel.",
          "- Contiene ácido hialurónico para ayudar a retener la humedad natural de la piel.",
          "- Hidratante tintado con SPF 30.",
          "- Puede llevarse solo o debajo del maquillaje como una imprimación teñida con SPF 30.",
          "",
          "Adecuado para todo tipo de piel:",
          "- Incluyendo piel seca, sensible, grasa y propensa al acné.",
          "- No viene con un sello protector.",
          "",
          "Tres ceramidas esenciales:",
          "- Las ceramidas se encuentran naturalmente en la piel y pueden dañarse con la exposición al sol.",
          "- Todos los productos CeraVe están formulados con tres ceramidas esenciales (1, 3, 6-II) para ayudar a restaurar y mantener la barrera natural de la piel.",
          "",
          "Fórmula segura y suave:",
          "- Sin oxibenzona, sin avobenzona y sin benceno.",
          "- Protector solar 100% mineral que contiene solo filtros físicos de óxido de zinc y dióxido de titanio.",
          "- Libre de parabenos, sin fragancia y no comedogénico.",
          "",
          "- Elegible para FSA y elegible para HSA"
        ],
        shortDescription: "Breve descripción del producto, enfocándose en sus características principales y beneficios clave para ofrecer una vista rápida de lo que el cliente puede esperar.",
        originalPrice: 200,
        color: "Negro",
        images: [
          "/Belleza/Maquillaje_46/e.l.f._1.jpg",
          "/Belleza/Maquillaje_46/e.l.f._2.jpg",
          "/Belleza/Maquillaje_46/e.l.f._3.jpg",
          "/Belleza/Maquillaje_46/e.l.f._4.jpg",
        ],
      },

      {
        id: "47",
        name: "Crema CeraVe Sistema de renovación de  48 gramos",
        price: 79900,
        image: "/Belleza/Crema_47/CeraVeSkinRenewing_1.jpg",
        rating: 5,
        filter: "Cremas Humectantes",
        category: "Belleza",
        fullDescription: [
          "Protector solar mineral tintado transparente:",
          "- Tinte universal para todos los tonos de piel.",
          "- Deja la piel con un brillo saludable al instante.",
          "- Compensa el yeso blanco típicamente asociado con los protectores solares minerales.",
          "- Ligero, sensación no grasa.",
          "",
          "Protector solar facial hidratante:",
          "- Formulado con niacinamida para calmar la piel.",
          "- Contiene ácido hialurónico para ayudar a retener la humedad natural de la piel.",
          "- Hidratante tintado con SPF 30.",
          "- Puede llevarse solo o debajo del maquillaje como una imprimación teñida con SPF 30.",
          "",
          "Adecuado para todo tipo de piel:",
          "- Incluyendo piel seca, sensible, grasa y propensa al acné.",
          "- No viene con un sello protector.",
          "",
          "Tres ceramidas esenciales:",
          "- Las ceramidas se encuentran naturalmente en la piel y pueden dañarse con la exposición al sol.",
          "- Todos los productos CeraVe están formulados con tres ceramidas esenciales (1, 3, 6-II) para ayudar a restaurar y mantener la barrera natural de la piel.",
          "",
          "Fórmula segura y suave:",
          "- Sin oxibenzona, sin avobenzona y sin benceno.",
          "- Protector solar 100% mineral que contiene solo filtros físicos de óxido de zinc y dióxido de titanio.",
          "- Libre de parabenos, sin fragancia y no comedogénico.",
          "",
          "- Elegible para FSA y elegible para HSA"
        ],
        shortDescription: "Breve descripción del producto, enfocándose en sus características principales y beneficios clave para ofrecer una vista rápida de lo que el cliente puede esperar.",
        originalPrice: 200,
        color: "Negro",
        images: [
          "/Belleza/Crema_47/CeraVeSkinRenewing_1.jpg",
          "/Belleza/Crema_47/CeraVeSkinRenewing_2.jpg",
          "/Belleza/Crema_47/CeraVeSkinRenewing_3.jpg",
          "/Belleza/Crema_47/CeraVeSkinRenewing_4.jpg",
          "/Belleza/Crema_47/CeraVeSkinRenewing_5.jpg",
          "/Belleza/Crema_47/CeraVeSkinRenewing_6.jpg",
        ],
      },

      {
        id: "48",
        name: "Maquillaje Vavalash - Kit de extensiones de pestañas para bricolaje 30D, 40D, 0.07D-10-16mm",
        price: 79900,
        image: "/Belleza/Maquillaje_48/vavalash_1.jpg",
        rating: 5,
        filter: "Maquillaje",
        category: "Belleza",
        fullDescription: [
          "Protector solar mineral tintado transparente:",
          "- Tinte universal para todos los tonos de piel.",
          "- Deja la piel con un brillo saludable al instante.",
          "- Compensa el yeso blanco típicamente asociado con los protectores solares minerales.",
          "- Ligero, sensación no grasa.",
          "",
          "Protector solar facial hidratante:",
          "- Formulado con niacinamida para calmar la piel.",
          "- Contiene ácido hialurónico para ayudar a retener la humedad natural de la piel.",
          "- Hidratante tintado con SPF 30.",
          "- Puede llevarse solo o debajo del maquillaje como una imprimación teñida con SPF 30.",
          "",
          "Adecuado para todo tipo de piel:",
          "- Incluyendo piel seca, sensible, grasa y propensa al acné.",
          "- No viene con un sello protector.",
          "",
          "Tres ceramidas esenciales:",
          "- Las ceramidas se encuentran naturalmente en la piel y pueden dañarse con la exposición al sol.",
          "- Todos los productos CeraVe están formulados con tres ceramidas esenciales (1, 3, 6-II) para ayudar a restaurar y mantener la barrera natural de la piel.",
          "",
          "Fórmula segura y suave:",
          "- Sin oxibenzona, sin avobenzona y sin benceno.",
          "- Protector solar 100% mineral que contiene solo filtros físicos de óxido de zinc y dióxido de titanio.",
          "- Libre de parabenos, sin fragancia y no comedogénico.",
          "",
          "- Elegible para FSA y elegible para HSA"
        ],
        shortDescription: "Breve descripción del producto, enfocándose en sus características principales y beneficios clave para ofrecer una vista rápida de lo que el cliente puede esperar.",
        originalPrice: 200,
        color: "Negro",
        images: [
          "/Belleza/Maquillaje_58/vavalash_1.jpg",
          "/Belleza/Maquillaje_58/vavalash_2.jpg",
          "/Belleza/Maquillaje_58/vavalash_3.jpg",
          "/Belleza/Maquillaje_58/vavalash_4.jpg",
          "/Belleza/Maquillaje_58/vavalash_5.jpg",
          "/Belleza/Maquillaje_58/vavalash_6.jpg",
          "/Belleza/Maquillaje_58/vavalash_7.jpg",
        ],
      },
      {
        id: "49",
        name: "Cetaphil Limpiador facial diario para pieles sensibles, combinadas con pieles grasas, espuma suave, sin jabón, hipoalergénico de 454 gramos",
        price: 79900,
        image: "/Belleza/Crema_49/CetaphilWashDaily_1.jpg",
        rating: 5,
        filter: "Cremas Humectantes",
        category: "Belleza",
        fullDescription: [
          "Protector solar mineral tintado transparente:",
          "- Tinte universal para todos los tonos de piel.",
          "- Deja la piel con un brillo saludable al instante.",
          "- Compensa el yeso blanco típicamente asociado con los protectores solares minerales.",
          "- Ligero, sensación no grasa.",
          "",
          "Protector solar facial hidratante:",
          "- Formulado con niacinamida para calmar la piel.",
          "- Contiene ácido hialurónico para ayudar a retener la humedad natural de la piel.",
          "- Hidratante tintado con SPF 30.",
          "- Puede llevarse solo o debajo del maquillaje como una imprimación teñida con SPF 30.",
          "",
          "Adecuado para todo tipo de piel:",
          "- Incluyendo piel seca, sensible, grasa y propensa al acné.",
          "- No viene con un sello protector.",
          "",
          "Tres ceramidas esenciales:",
          "- Las ceramidas se encuentran naturalmente en la piel y pueden dañarse con la exposición al sol.",
          "- Todos los productos CeraVe están formulados con tres ceramidas esenciales (1, 3, 6-II) para ayudar a restaurar y mantener la barrera natural de la piel.",
          "",
          "Fórmula segura y suave:",
          "- Sin oxibenzona, sin avobenzona y sin benceno.",
          "- Protector solar 100% mineral que contiene solo filtros físicos de óxido de zinc y dióxido de titanio.",
          "- Libre de parabenos, sin fragancia y no comedogénico.",
          "",
          "- Elegible para FSA y elegible para HSA"
        ],
        shortDescription: "Breve descripción del producto, enfocándose en sus características principales y beneficios clave para ofrecer una vista rápida de lo que el cliente puede esperar.",
        originalPrice: 200,
        color: "Negro",
        images: [
          "/Belleza/Crema_49/CetaphilWashDaily_1.jpg",
          "/Belleza/Crema_49/CetaphilWashDaily_2.jpg",
          "/Belleza/Crema_49/CetaphilWashDaily_3.jpg",
          "/Belleza/Crema_49/CetaphilWashDaily_4.jpg",
          "/Belleza/Crema_49/CetaphilWashDaily_5.jpg",
          "/Belleza/Crema_49/CetaphilWashDaily_6.jpg",
        ],
      },

      {
        id: "50",
        name: "Desconocido por ahora",
        price: 79900,
        image: "/Belleza/Maquillaje_50/",
        rating: 5,
        filter: "Maquillaje",
        category: "Belleza",
        fullDescription: [
          "Protector solar mineral tintado transparente:",
          "- Tinte universal para todos los tonos de piel.",
          "- Deja la piel con un brillo saludable al instante.",
          "- Compensa el yeso blanco típicamente asociado con los protectores solares minerales.",
          "- Ligero, sensación no grasa.",
          "",
          "Protector solar facial hidratante:",
          "- Formulado con niacinamida para calmar la piel.",
          "- Contiene ácido hialurónico para ayudar a retener la humedad natural de la piel.",
          "- Hidratante tintado con SPF 30.",
          "- Puede llevarse solo o debajo del maquillaje como una imprimación teñida con SPF 30.",
          "",
          "Adecuado para todo tipo de piel:",
          "- Incluyendo piel seca, sensible, grasa y propensa al acné.",
          "- No viene con un sello protector.",
          "",
          "Tres ceramidas esenciales:",
          "- Las ceramidas se encuentran naturalmente en la piel y pueden dañarse con la exposición al sol.",
          "- Todos los productos CeraVe están formulados con tres ceramidas esenciales (1, 3, 6-II) para ayudar a restaurar y mantener la barrera natural de la piel.",
          "",
          "Fórmula segura y suave:",
          "- Sin oxibenzona, sin avobenzona y sin benceno.",
          "- Protector solar 100% mineral que contiene solo filtros físicos de óxido de zinc y dióxido de titanio.",
          "- Libre de parabenos, sin fragancia y no comedogénico.",
          "",
          "- Elegible para FSA y elegible para HSA"
        ],
        shortDescription: "Breve descripción del producto, enfocándose en sus características principales y beneficios clave para ofrecer una vista rápida de lo que el cliente puede esperar.",
        originalPrice: 200,
        color: "Negro",
        images: [
          "/Belleza/Maquillaje_58/vavalash_1.jpg",
          "/Belleza/Maquillaje_58/vavalash_2.jpg",
          "/Belleza/Maquillaje_58/vavalash_3.jpg",
          "/Belleza/Maquillaje_58/vavalash_4.jpg",
          "/Belleza/Maquillaje_58/vavalash_5.jpg",
          "/Belleza/Maquillaje_58/vavalash_6.jpg",
          "/Belleza/Maquillaje_58/vavalash_7.jpg",
        ],
      },
    
    
      
     
      
        {
          id: "4",
          name: "[Certificado Apple MFi] Paquete de 6 cargadores de iPhone (3/3/6/6/6/10 pies)",
          price: 41904,
          image: "/tecnologia/CablesCargadores.jpg",
          rating: 5,
          filter: "Accesorios",
          category: "Tecnologia",
          fullDescription: [
          "Protector solar mineral tintado transparente:",
          "- Tinte universal para todos los tonos de piel.",
          "- Deja la piel con un brillo saludable al instante.",
          "- Compensa el yeso blanco típicamente asociado con los protectores solares minerales.",
          "- Ligero, sensación no grasa.",
          "",
          "Protector solar facial hidratante:",
          "- Formulado con niacinamida para calmar la piel.",
          "- Contiene ácido hialurónico para ayudar a retener la humedad natural de la piel.",
          "- Hidratante tintado con SPF 30.",
          "- Puede llevarse solo o debajo del maquillaje como una imprimación teñida con SPF 30.",
          "",
          "Adecuado para todo tipo de piel:",
          "- Incluyendo piel seca, sensible, grasa y propensa al acné.",
          "- No viene con un sello protector.",
          "",
          "Tres ceramidas esenciales:",
          "- Las ceramidas se encuentran naturalmente en la piel y pueden dañarse con la exposición al sol.",
          "- Todos los productos CeraVe están formulados con tres ceramidas esenciales (1, 3, 6-II) para ayudar a restaurar y mantener la barrera natural de la piel.",
          "",
          "Fórmula segura y suave:",
          "- Sin oxibenzona, sin avobenzona y sin benceno.",
          "- Protector solar 100% mineral que contiene solo filtros físicos de óxido de zinc y dióxido de titanio.",
          "- Libre de parabenos, sin fragancia y no comedogénico.",
          "",
          "- Elegible para FSA y elegible para HSA"
        ],
        shortDescription: "Breve descripción del producto, enfocándose en sus características principales y beneficios clave para ofrecer una vista rápida de lo que el cliente puede esperar.",
        originalPrice: 200,
        color: "Negro",
        images: [
          "/Belleza/Maquillaje_58/vavalash_1.jpg",
          "/Belleza/Maquillaje_58/vavalash_2.jpg",
          "/Belleza/Maquillaje_58/vavalash_3.jpg",
          "/Belleza/Maquillaje_58/vavalash_4.jpg",
          "/Belleza/Maquillaje_58/vavalash_5.jpg",
          "/Belleza/Maquillaje_58/vavalash_6.jpg",
          "/Belleza/Maquillaje_58/vavalash_7.jpg",
        ],
          
        },
      
        {
          id: "5",
          name: "Sceptre LED - Monitor de 22 pulgadas 1080p 75Hz",
          price: 75550,
          image: "/tecnologia/MonitorLED.jpg",
          rating: 5,
          filter: "Monitores",
          category: "Tecnologia",
          fullDescription: [
          "Protector solar mineral tintado transparente:",
          "- Tinte universal para todos los tonos de piel.",
          "- Deja la piel con un brillo saludable al instante.",
          "- Compensa el yeso blanco típicamente asociado con los protectores solares minerales.",
          "- Ligero, sensación no grasa.",
          "",
          "Protector solar facial hidratante:",
          "- Formulado con niacinamida para calmar la piel.",
          "- Contiene ácido hialurónico para ayudar a retener la humedad natural de la piel.",
          "- Hidratante tintado con SPF 30.",
          "- Puede llevarse solo o debajo del maquillaje como una imprimación teñida con SPF 30.",
          "",
          "Adecuado para todo tipo de piel:",
          "- Incluyendo piel seca, sensible, grasa y propensa al acné.",
          "- No viene con un sello protector.",
          "",
          "Tres ceramidas esenciales:",
          "- Las ceramidas se encuentran naturalmente en la piel y pueden dañarse con la exposición al sol.",
          "- Todos los productos CeraVe están formulados con tres ceramidas esenciales (1, 3, 6-II) para ayudar a restaurar y mantener la barrera natural de la piel.",
          "",
          "Fórmula segura y suave:",
          "- Sin oxibenzona, sin avobenzona y sin benceno.",
          "- Protector solar 100% mineral que contiene solo filtros físicos de óxido de zinc y dióxido de titanio.",
          "- Libre de parabenos, sin fragancia y no comedogénico.",
          "",
          "- Elegible para FSA y elegible para HSA"
        ],
        shortDescription: "Breve descripción del producto, enfocándose en sus características principales y beneficios clave para ofrecer una vista rápida de lo que el cliente puede esperar.",
        originalPrice: 200,
        color: "Negro",
        images: [
          "/Belleza/Maquillaje_58/vavalash_1.jpg",
          "/Belleza/Maquillaje_58/vavalash_2.jpg",
          "/Belleza/Maquillaje_58/vavalash_3.jpg",
          "/Belleza/Maquillaje_58/vavalash_4.jpg",
          "/Belleza/Maquillaje_58/vavalash_5.jpg",
          "/Belleza/Maquillaje_58/vavalash_6.jpg",
          "/Belleza/Maquillaje_58/vavalash_7.jpg",
        ],
          
        },
      
        {
          id: "6",
          name: " TRIGKEY Mini PC Ryzen 7 W11 Pro Desktop",
          price: 1295400,
          image: "/Mini_PC.png",
          rating: 5,
          filter: "Computadores",
          category: "Tecnologia",
          fullDescription: [
          "Protector solar mineral tintado transparente:",
          "- Tinte universal para todos los tonos de piel.",
          "- Deja la piel con un brillo saludable al instante.",
          "- Compensa el yeso blanco típicamente asociado con los protectores solares minerales.",
          "- Ligero, sensación no grasa.",
          "",
          "Protector solar facial hidratante:",
          "- Formulado con niacinamida para calmar la piel.",
          "- Contiene ácido hialurónico para ayudar a retener la humedad natural de la piel.",
          "- Hidratante tintado con SPF 30.",
          "- Puede llevarse solo o debajo del maquillaje como una imprimación teñida con SPF 30.",
          "",
          "Adecuado para todo tipo de piel:",
          "- Incluyendo piel seca, sensible, grasa y propensa al acné.",
          "- No viene con un sello protector.",
          "",
          "Tres ceramidas esenciales:",
          "- Las ceramidas se encuentran naturalmente en la piel y pueden dañarse con la exposición al sol.",
          "- Todos los productos CeraVe están formulados con tres ceramidas esenciales (1, 3, 6-II) para ayudar a restaurar y mantener la barrera natural de la piel.",
          "",
          "Fórmula segura y suave:",
          "- Sin oxibenzona, sin avobenzona y sin benceno.",
          "- Protector solar 100% mineral que contiene solo filtros físicos de óxido de zinc y dióxido de titanio.",
          "- Libre de parabenos, sin fragancia y no comedogénico.",
          "",
          "- Elegible para FSA y elegible para HSA"
        ],
        shortDescription: "Breve descripción del producto, enfocándose en sus características principales y beneficios clave para ofrecer una vista rápida de lo que el cliente puede esperar.",
        originalPrice: 200,
        color: "Negro",
        images: [
          "/Belleza/Maquillaje_58/vavalash_1.jpg",
          "/Belleza/Maquillaje_58/vavalash_2.jpg",
          "/Belleza/Maquillaje_58/vavalash_3.jpg",
          "/Belleza/Maquillaje_58/vavalash_4.jpg",
          "/Belleza/Maquillaje_58/vavalash_5.jpg",
          "/Belleza/Maquillaje_58/vavalash_6.jpg",
          "/Belleza/Maquillaje_58/vavalash_7.jpg",
        ],
          
        },
      
        {
          id: "7",
          name: "Auriculares inalámbricos Bluetooth V5.3, reproducción de 50 horas",
          price: 79990,
          image: "/tecnologia/Audifonos2.jpg",
          rating: 5,
          filter: "Audífonos",
          category: "Tecnologia",
          fullDescription: [
          "Protector solar mineral tintado transparente:",
          "- Tinte universal para todos los tonos de piel.",
          "- Deja la piel con un brillo saludable al instante.",
          "- Compensa el yeso blanco típicamente asociado con los protectores solares minerales.",
          "- Ligero, sensación no grasa.",
          "",
          "Protector solar facial hidratante:",
          "- Formulado con niacinamida para calmar la piel.",
          "- Contiene ácido hialurónico para ayudar a retener la humedad natural de la piel.",
          "- Hidratante tintado con SPF 30.",
          "- Puede llevarse solo o debajo del maquillaje como una imprimación teñida con SPF 30.",
          "",
          "Adecuado para todo tipo de piel:",
          "- Incluyendo piel seca, sensible, grasa y propensa al acné.",
          "- No viene con un sello protector.",
          "",
          "Tres ceramidas esenciales:",
          "- Las ceramidas se encuentran naturalmente en la piel y pueden dañarse con la exposición al sol.",
          "- Todos los productos CeraVe están formulados con tres ceramidas esenciales (1, 3, 6-II) para ayudar a restaurar y mantener la barrera natural de la piel.",
          "",
          "Fórmula segura y suave:",
          "- Sin oxibenzona, sin avobenzona y sin benceno.",
          "- Protector solar 100% mineral que contiene solo filtros físicos de óxido de zinc y dióxido de titanio.",
          "- Libre de parabenos, sin fragancia y no comedogénico.",
          "",
          "- Elegible para FSA y elegible para HSA"
        ],
        shortDescription: "Breve descripción del producto, enfocándose en sus características principales y beneficios clave para ofrecer una vista rápida de lo que el cliente puede esperar.",
        originalPrice: 200,
        color: "Negro",
        images: [
          "/Belleza/Maquillaje_58/vavalash_1.jpg",
          "/Belleza/Maquillaje_58/vavalash_2.jpg",
          "/Belleza/Maquillaje_58/vavalash_3.jpg",
          "/Belleza/Maquillaje_58/vavalash_4.jpg",
          "/Belleza/Maquillaje_58/vavalash_5.jpg",
          "/Belleza/Maquillaje_58/vavalash_6.jpg",
          "/Belleza/Maquillaje_58/vavalash_7.jpg",
        ],
          
        },
      
        {
          id: "8",
          name: "UGREEN Revodok USB C Hub 5 en 1 ",
          price: 79990,
          image: "/tecnologia/USBHUB.jpg",
          rating: 5,
          filter: "Accesorios",
          category: "Tecnologia",
          fullDescription: [
          "Protector solar mineral tintado transparente:",
          "- Tinte universal para todos los tonos de piel.",
          "- Deja la piel con un brillo saludable al instante.",
          "- Compensa el yeso blanco típicamente asociado con los protectores solares minerales.",
          "- Ligero, sensación no grasa.",
          "",
          "Protector solar facial hidratante:",
          "- Formulado con niacinamida para calmar la piel.",
          "- Contiene ácido hialurónico para ayudar a retener la humedad natural de la piel.",
          "- Hidratante tintado con SPF 30.",
          "- Puede llevarse solo o debajo del maquillaje como una imprimación teñida con SPF 30.",
          "",
          "Adecuado para todo tipo de piel:",
          "- Incluyendo piel seca, sensible, grasa y propensa al acné.",
          "- No viene con un sello protector.",
          "",
          "Tres ceramidas esenciales:",
          "- Las ceramidas se encuentran naturalmente en la piel y pueden dañarse con la exposición al sol.",
          "- Todos los productos CeraVe están formulados con tres ceramidas esenciales (1, 3, 6-II) para ayudar a restaurar y mantener la barrera natural de la piel.",
          "",
          "Fórmula segura y suave:",
          "- Sin oxibenzona, sin avobenzona y sin benceno.",
          "- Protector solar 100% mineral que contiene solo filtros físicos de óxido de zinc y dióxido de titanio.",
          "- Libre de parabenos, sin fragancia y no comedogénico.",
          "",
          "- Elegible para FSA y elegible para HSA"
        ],
        shortDescription: "Breve descripción del producto, enfocándose en sus características principales y beneficios clave para ofrecer una vista rápida de lo que el cliente puede esperar.",
        originalPrice: 200,
        color: "Negro",
        images: [
          "/Belleza/Maquillaje_58/vavalash_1.jpg",
          "/Belleza/Maquillaje_58/vavalash_2.jpg",
          "/Belleza/Maquillaje_58/vavalash_3.jpg",
          "/Belleza/Maquillaje_58/vavalash_4.jpg",
          "/Belleza/Maquillaje_58/vavalash_5.jpg",
          "/Belleza/Maquillaje_58/vavalash_6.jpg",
          "/Belleza/Maquillaje_58/vavalash_7.jpg",
        ],
          
        },
      
        {
          id: "9",
          name: "Beelink Mini PC S12 Pro",
          price: 79990,
          image: "/tecnologia/Mini_PCINTEL.jpg",
          rating: 5,
          filter: "Computadores",
          category: "Tecnologia",
          fullDescription: [
          "Protector solar mineral tintado transparente:",
          "- Tinte universal para todos los tonos de piel.",
          "- Deja la piel con un brillo saludable al instante.",
          "- Compensa el yeso blanco típicamente asociado con los protectores solares minerales.",
          "- Ligero, sensación no grasa.",
          "",
          "Protector solar facial hidratante:",
          "- Formulado con niacinamida para calmar la piel.",
          "- Contiene ácido hialurónico para ayudar a retener la humedad natural de la piel.",
          "- Hidratante tintado con SPF 30.",
          "- Puede llevarse solo o debajo del maquillaje como una imprimación teñida con SPF 30.",
          "",
          "Adecuado para todo tipo de piel:",
          "- Incluyendo piel seca, sensible, grasa y propensa al acné.",
          "- No viene con un sello protector.",
          "",
          "Tres ceramidas esenciales:",
          "- Las ceramidas se encuentran naturalmente en la piel y pueden dañarse con la exposición al sol.",
          "- Todos los productos CeraVe están formulados con tres ceramidas esenciales (1, 3, 6-II) para ayudar a restaurar y mantener la barrera natural de la piel.",
          "",
          "Fórmula segura y suave:",
          "- Sin oxibenzona, sin avobenzona y sin benceno.",
          "- Protector solar 100% mineral que contiene solo filtros físicos de óxido de zinc y dióxido de titanio.",
          "- Libre de parabenos, sin fragancia y no comedogénico.",
          "",
          "- Elegible para FSA y elegible para HSA"
        ],
        shortDescription: "Breve descripción del producto, enfocándose en sus características principales y beneficios clave para ofrecer una vista rápida de lo que el cliente puede esperar.",
        originalPrice: 200,
        color: "Negro",
        images: [
          "/Belleza/Maquillaje_58/vavalash_1.jpg",
          "/Belleza/Maquillaje_58/vavalash_2.jpg",
          "/Belleza/Maquillaje_58/vavalash_3.jpg",
          "/Belleza/Maquillaje_58/vavalash_4.jpg",
          "/Belleza/Maquillaje_58/vavalash_5.jpg",
          "/Belleza/Maquillaje_58/vavalash_6.jpg",
          "/Belleza/Maquillaje_58/vavalash_7.jpg",
        ],
          
        },
      
        {
          id: "10",
          name: "Auriculares inalámbricos Bluetooth V5.3, reproducción de 50 horas",
          price: 79990,
          image: "/tecnologia/Audifonos2.jpg",
          rating: 5,
          filter: "Audífonos",
          category: "Tecnologia",
          fullDescription: [
          "Protector solar mineral tintado transparente:",
          "- Tinte universal para todos los tonos de piel.",
          "- Deja la piel con un brillo saludable al instante.",
          "- Compensa el yeso blanco típicamente asociado con los protectores solares minerales.",
          "- Ligero, sensación no grasa.",
          "",
          "Protector solar facial hidratante:",
          "- Formulado con niacinamida para calmar la piel.",
          "- Contiene ácido hialurónico para ayudar a retener la humedad natural de la piel.",
          "- Hidratante tintado con SPF 30.",
          "- Puede llevarse solo o debajo del maquillaje como una imprimación teñida con SPF 30.",
          "",
          "Adecuado para todo tipo de piel:",
          "- Incluyendo piel seca, sensible, grasa y propensa al acné.",
          "- No viene con un sello protector.",
          "",
          "Tres ceramidas esenciales:",
          "- Las ceramidas se encuentran naturalmente en la piel y pueden dañarse con la exposición al sol.",
          "- Todos los productos CeraVe están formulados con tres ceramidas esenciales (1, 3, 6-II) para ayudar a restaurar y mantener la barrera natural de la piel.",
          "",
          "Fórmula segura y suave:",
          "- Sin oxibenzona, sin avobenzona y sin benceno.",
          "- Protector solar 100% mineral que contiene solo filtros físicos de óxido de zinc y dióxido de titanio.",
          "- Libre de parabenos, sin fragancia y no comedogénico.",
          "",
          "- Elegible para FSA y elegible para HSA"
        ],
        shortDescription: "Breve descripción del producto, enfocándose en sus características principales y beneficios clave para ofrecer una vista rápida de lo que el cliente puede esperar.",
        originalPrice: 200,
        color: "Negro",
        images: [
          "/Belleza/Maquillaje_58/vavalash_1.jpg",
          "/Belleza/Maquillaje_58/vavalash_2.jpg",
          "/Belleza/Maquillaje_58/vavalash_3.jpg",
          "/Belleza/Maquillaje_58/vavalash_4.jpg",
          "/Belleza/Maquillaje_58/vavalash_5.jpg",
          "/Belleza/Maquillaje_58/vavalash_6.jpg",
          "/Belleza/Maquillaje_58/vavalash_7.jpg",
        ],
          
        },
      
        {
          id: "11",
          name: "Spray limpiador de pantalla (16 onzas)",
          price: 47990,
          image: "/tecnologia/limpiadorpantalla.jpg",
          rating: 5,
          filter: "Audífonos",
          category: "Tecnologia",
          fullDescription: [
          "Protector solar mineral tintado transparente:",
          "- Tinte universal para todos los tonos de piel.",
          "- Deja la piel con un brillo saludable al instante.",
          "- Compensa el yeso blanco típicamente asociado con los protectores solares minerales.",
          "- Ligero, sensación no grasa.",
          "",
          "Protector solar facial hidratante:",
          "- Formulado con niacinamida para calmar la piel.",
          "- Contiene ácido hialurónico para ayudar a retener la humedad natural de la piel.",
          "- Hidratante tintado con SPF 30.",
          "- Puede llevarse solo o debajo del maquillaje como una imprimación teñida con SPF 30.",
          "",
          "Adecuado para todo tipo de piel:",
          "- Incluyendo piel seca, sensible, grasa y propensa al acné.",
          "- No viene con un sello protector.",
          "",
          "Tres ceramidas esenciales:",
          "- Las ceramidas se encuentran naturalmente en la piel y pueden dañarse con la exposición al sol.",
          "- Todos los productos CeraVe están formulados con tres ceramidas esenciales (1, 3, 6-II) para ayudar a restaurar y mantener la barrera natural de la piel.",
          "",
          "Fórmula segura y suave:",
          "- Sin oxibenzona, sin avobenzona y sin benceno.",
          "- Protector solar 100% mineral que contiene solo filtros físicos de óxido de zinc y dióxido de titanio.",
          "- Libre de parabenos, sin fragancia y no comedogénico.",
          "",
          "- Elegible para FSA y elegible para HSA"
        ],
        shortDescription: "Breve descripción del producto, enfocándose en sus características principales y beneficios clave para ofrecer una vista rápida de lo que el cliente puede esperar.",
        originalPrice: 200,
        color: "Negro",
        images: [
          "/Belleza/Maquillaje_58/vavalash_1.jpg",
          "/Belleza/Maquillaje_58/vavalash_2.jpg",
          "/Belleza/Maquillaje_58/vavalash_3.jpg",
          "/Belleza/Maquillaje_58/vavalash_4.jpg",
          "/Belleza/Maquillaje_58/vavalash_5.jpg",
          "/Belleza/Maquillaje_58/vavalash_6.jpg",
          "/Belleza/Maquillaje_58/vavalash_7.jpg",
        ],
          
        },
      
        {
          id: "12",
          name: "Auriculares inalámbricos Bluetooth V5.3, reproducción de 50 horas",
          price: 79990,
          image: "/tecnologia/Audifonos2.jpg",
          rating: 5,
          filter: "Audífonos",
          category: "Tecnologia",
          fullDescription: [
          "Protector solar mineral tintado transparente:",
          "- Tinte universal para todos los tonos de piel.",
          "- Deja la piel con un brillo saludable al instante.",
          "- Compensa el yeso blanco típicamente asociado con los protectores solares minerales.",
          "- Ligero, sensación no grasa.",
          "",
          "Protector solar facial hidratante:",
          "- Formulado con niacinamida para calmar la piel.",
          "- Contiene ácido hialurónico para ayudar a retener la humedad natural de la piel.",
          "- Hidratante tintado con SPF 30.",
          "- Puede llevarse solo o debajo del maquillaje como una imprimación teñida con SPF 30.",
          "",
          "Adecuado para todo tipo de piel:",
          "- Incluyendo piel seca, sensible, grasa y propensa al acné.",
          "- No viene con un sello protector.",
          "",
          "Tres ceramidas esenciales:",
          "- Las ceramidas se encuentran naturalmente en la piel y pueden dañarse con la exposición al sol.",
          "- Todos los productos CeraVe están formulados con tres ceramidas esenciales (1, 3, 6-II) para ayudar a restaurar y mantener la barrera natural de la piel.",
          "",
          "Fórmula segura y suave:",
          "- Sin oxibenzona, sin avobenzona y sin benceno.",
          "- Protector solar 100% mineral que contiene solo filtros físicos de óxido de zinc y dióxido de titanio.",
          "- Libre de parabenos, sin fragancia y no comedogénico.",
          "",
          "- Elegible para FSA y elegible para HSA"
        ],
        shortDescription: "Breve descripción del producto, enfocándose en sus características principales y beneficios clave para ofrecer una vista rápida de lo que el cliente puede esperar.",
        originalPrice: 200,
        color: "Negro",
        images: [
          "/Belleza/Maquillaje_58/vavalash_1.jpg",
          "/Belleza/Maquillaje_58/vavalash_2.jpg",
          "/Belleza/Maquillaje_58/vavalash_3.jpg",
          "/Belleza/Maquillaje_58/vavalash_4.jpg",
          "/Belleza/Maquillaje_58/vavalash_5.jpg",
          "/Belleza/Maquillaje_58/vavalash_6.jpg",
          "/Belleza/Maquillaje_58/vavalash_7.jpg",
        ],
          
        },
      ]
  };
